language: node_js
node_js:
  - stable
sudo: false
before_install:
  - npm install -g npm@latest
install:
  - cp .env.example .env
  - npm i
  - npm install --save request -g
  - npm ci
cache:
  directories:
    - "node_modules"
