version: '3'
services:
  ogun_base:
    build:
      context: .
      dockerfile: DockerFile.base
    image: ogun_base:latest
  app:
    container_name: ogun_community_api
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - ogun_base
      - db
    environment:
      - SERVER_ENV=development
    ports:
      - "3333:3333"
      - "8212:80"
    volumes:
      - ${PWD}:/code
      - ${PWD}/storage/logs:/tmp/logs
  db:
    image: mysql:5.6
    ports:
      - "3307:3306"
    volumes:
      - "${PWD}/storage/mysql/mysql_conf_d:/etc/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=oguncommunity
      - MYSQL_DATABASE=ogun_community

